---
web_app_name: devops-info-service
web_app_port: 8000
web_app_internal_port: 5000
web_app_container_name: "{{ web_app_name }}"
web_app_docker_image: "{{ dockerhub_username }}/{{ web_app_name }}"
web_app_docker_tag: latest
web_app_restart_policy: unless-stopped
web_app_wipe: false
